name: Build Cordova Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
  ANDROID_HOME: /usr/local/lib/android/sdk
  JAVA_HOME: /usr/lib/jvm/temurin-11-jdk-amd64
  GRADLE_USER_HOME: /home/runner/.gradle

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    # 1. Configuração do Java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    # 2. Configuração completa do Android
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        ndk-version: '25.1.8937393'
        cmake-version: '3.22.1'

    # 3. Instalação do Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 4. Dependências do sistema
    - name: Install system dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install -y libglu1 libsm6 libxi6 libxrender1 libfontconfig1

    # 5. Configuração do Cordova
    - name: Install Cordova and check requirements
      run: |
        npm install -g cordova
        cordova telemetry off
        cordova requirements

    # 6. Adicionar plataforma Android
    - name: Add Android platform
      run: |
        cordova platform remove android
        cordova platform add android@11.0.0

    # 7. Build com debug detalhado
    - name: Build Android APK
      run: |
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        cordova build android --release --verbose
        ls -la platforms/android/app/build/outputs/apk/release/

    # 8. Upload do APK
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: platforms/android/app/build/outputs/apk/release/*.apk
        retention-days: 5
